var isDone = false;
console.log("isDone is " + isDone);
var decimal = 6;
var hex = 0xf00d;
var binary = 10;
var octal = 484;
console.log("Decimal is " + decimal + "\nHex is " + hex + "\nbinary is " + binary + "\noctal is " + octal);
var color = "blue";
console.log(color);
color = "red";
console.log(color);
var fullName = "Bob Bobby";
var age = 6;
var sentence = "Hello, my name is " + fullName + ".\n\nI'll be " + (age + 1) + " years next month.";
console.log(sentence);
var list = [1, 2, 3];
var list2 = [4, 5, 6];
var num;
for (num = 0; num < list.length; num++) {
    console.log(list[num]);
    console.log(list2[num]);
}
var x;
x = ["hello", 10];
console.log(x[0].substr(1));
console.log(x[1].toString());
x[3] = "world";
console.log(x[3]);
var Color;
(function (Color) {
    Color[Color["Red"] = 1] = "Red";
    Color[Color["Green"] = 2] = "Green";
    Color[Color["Blue"] = 3] = "Blue";
})(Color || (Color = {}));
var c = Color.Green;
console.log(c);
var colorName = Color[3];
console.log(colorName);
var notSure = 4;
console.log(notSure);
notSure = "maybe a string";
console.log(notSure);
notSure = false;
console.log(notSure);
